"""edit departure

Revision ID: 02174483b678
Revises: f35143eab986
Create Date: 2022-01-26 13:39:30.602160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02174483b678'
down_revision = 'f35143eab986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departure', sa.Column('agent', sa.String(length=250), nullable=True))
    op.drop_constraint('departure_req_ibfk_4', 'departure_req', type_='foreignkey')
    op.drop_column('departure_req', 'agents_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departure_req', sa.Column('agents_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('departure_req_ibfk_4', 'departure_req', 'agents', ['agents_id'], ['id'])
    op.drop_column('departure', 'agent')
    # ### end Alembic commands ###
