"""edit stock

Revision ID: 072479d6028d
Revises: 7e2bbb7d7361
Create Date: 2022-06-30 17:58:36.044112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '072479d6028d'
down_revision = '7e2bbb7d7361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderingitems')
    op.add_column('stock', sa.Column('order_quantity', sa.Integer(), nullable=True))
    op.drop_constraint('stock_ibfk_3', 'stock', type_='foreignkey')
    op.create_foreign_key(None, 'stock', 'orders', ['stock_order'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_foreign_key('stock_ibfk_3', 'stock', 'orderingitems', ['stock_order'], ['id'])
    op.drop_column('stock', 'order_quantity')
    op.create_table('orderingitems',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('deliveryNote', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deliveryNote'], ['orders.id'], name='orderingitems_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
