"""edit TLs profiles

Revision ID: 08375a3602bf
Revises: b4396d7a6d9e
Create Date: 2022-03-10 14:49:35.154410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08375a3602bf'
down_revision = 'b4396d7a6d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tls', sa.Column('role', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tls', 'role')
    # ### end Alembic commands ###
