"""edit leavers table

Revision ID: 148c19b22250
Revises: cb3edfe2af44
Create Date: 2022-01-18 18:18:07.142842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148c19b22250'
down_revision = 'cb3edfe2af44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leavers', sa.Column('manager', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leavers', 'manager')
    # ### end Alembic commands ###
