"""add tls team

Revision ID: 1d122d30c482
Revises: f1259a9a4f7a
Create Date: 2022-03-11 23:15:46.287980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d122d30c482'
down_revision = 'f1259a9a4f7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tlteam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tl', sa.Integer(), nullable=True),
    sa.Column('agent', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['tl'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tlteam')
    # ### end Alembic commands ###
