"""add notifications

Revision ID: 2481ee5f6648
Revises: d61f3cf10609
Create Date: 2022-02-15 03:11:31.856273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2481ee5f6648'
down_revision = 'd61f3cf10609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('body', sa.String(length=250), nullable=True),
    sa.Column('action', sa.String(length=250), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('dep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dep_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
