"""edit departure

Revision ID: 303fc0875e13
Revises: 5c821cf6a3b2
Create Date: 2022-01-26 10:51:46.097102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303fc0875e13'
down_revision = '5c821cf6a3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('it_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departure')
    op.drop_table('security_check')
    op.drop_table('it_check')
    op.drop_table('facility_check')
    # ### end Alembic commands ###
