"""edit departure

Revision ID: 37c4644e38ed
Revises: 9d7d5244967f
Create Date: 2022-01-26 14:34:14.858134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c4644e38ed'
down_revision = '9d7d5244967f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departure', sa.Column('facility_id', sa.Integer(), nullable=True))
    op.add_column('departure', sa.Column('it_id', sa.Integer(), nullable=True))
    op.add_column('departure', sa.Column('security_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departure', 'facilitycheck', ['facility_id'], ['id'])
    op.create_foreign_key(None, 'departure', 'securitycheck', ['security_id'], ['id'])
    op.create_foreign_key(None, 'departure', 'itcheck', ['it_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departure', type_='foreignkey')
    op.drop_constraint(None, 'departure', type_='foreignkey')
    op.drop_constraint(None, 'departure', type_='foreignkey')
    op.drop_column('departure', 'security_id')
    op.drop_column('departure', 'it_id')
    op.drop_column('departure', 'facility_id')
    # ### end Alembic commands ###
