"""edit users

Revision ID: 4343ca55eb66
Revises: 48d1667570eb
Create Date: 2022-01-27 14:03:55.293447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4343ca55eb66'
down_revision = '48d1667570eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'depart',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'department', ['depart'], ['id'])
    op.drop_column('users', 'depart_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('depart_name', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_1', 'users', 'department', ['depart_name'], ['id'])
    op.alter_column('users', 'depart',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
