"""add requists department

Revision ID: 4b42a8244f77
Revises: 90eb57792a6f
Create Date: 2022-02-07 03:34:01.344718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b42a8244f77'
down_revision = '90eb57792a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('depart_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'department', ['depart_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'depart_id')
    # ### end Alembic commands ###
