"""edit stock in

Revision ID: 4d30a915b037
Revises: 4c450964e5f1
Create Date: 2022-05-24 19:57:21.770701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d30a915b037'
down_revision = '4c450964e5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_ibfk_2', 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'item')
    op.add_column('stock', sa.Column('stock_order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock', 'order_items', ['stock_order'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'stock_order')
    op.add_column('order_items', sa.Column('item', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('order_items_ibfk_2', 'order_items', 'stock', ['item'], ['id'])
    # ### end Alembic commands ###
