"""add tickets

Revision ID: 5d4072ab3f73
Revises: 466f3231cf73
Create Date: 2022-03-09 12:25:30.661208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d4072ab3f73'
down_revision = '466f3231cf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('tick_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'requests', 'tickets', ['tick_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'tick_id')
    # ### end Alembic commands ###
