"""empty message

Revision ID: 61178c51b416
Revises: 386b84060afa
Create Date: 2022-05-24 20:16:04.732880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61178c51b416'
down_revision = '386b84060afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('deliveryNote', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'orders', ['deliveryNote'], ['id'])
    op.add_column('orders', sa.Column('title', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('stock', sa.Column('stock_order', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock', 'order_items', ['stock_order'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'stock_order')
    op.drop_column('orders', 'date')
    op.drop_column('orders', 'title')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'quantity')
    op.drop_column('order_items', 'deliveryNote')
    # ### end Alembic commands ###
