"""edit departure

Revision ID: 6220ac66be37
Revises: 02174483b678
Create Date: 2022-01-26 13:49:59.807570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6220ac66be37'
down_revision = '02174483b678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('departure_req_ibfk_2', 'departure_req', type_='foreignkey')
    op.drop_constraint('departure_req_ibfk_3', 'departure_req', type_='foreignkey')
    op.drop_column('departure_req', 'it_id')
    op.drop_column('departure_req', 'security_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departure_req', sa.Column('security_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('departure_req', sa.Column('it_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('departure_req_ibfk_3', 'departure_req', 'security_check', ['security_id'], ['id'])
    op.create_foreign_key('departure_req_ibfk_2', 'departure_req', 'it_check', ['it_id'], ['id'])
    # ### end Alembic commands ###
