"""edit departure

Revision ID: 788fc83d456b
Revises: 98fc6c4becd6
Create Date: 2022-01-26 17:20:31.027445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '788fc83d456b'
down_revision = '98fc6c4becd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departure', sa.Column('agent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'departure', 'agents', ['agent_id'], ['id'])
    op.drop_column('departure', 'agent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departure', sa.Column('agent', mysql.VARCHAR(length=250), nullable=True))
    op.drop_constraint(None, 'departure', type_='foreignkey')
    op.drop_column('departure', 'agent_id')
    # ### end Alembic commands ###
