"""empty message

Revision ID: 7e2bbb7d7361
Revises: 392ab19b1477
Create Date: 2022-05-24 22:03:13.371775

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e2bbb7d7361'
down_revision = '392ab19b1477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orderingitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deliveryNote', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deliveryNote'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orderitems')
    op.create_foreign_key(None, 'stock', 'orderingitems', ['stock_order'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.create_table('orderitems',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('deliveryNote', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['deliveryNote'], ['orders.id'], name='orderitems_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('orderingitems')
    # ### end Alembic commands ###
