"""edit tls team

Revision ID: 8916cdc8066a
Revises: 1d122d30c482
Create Date: 2022-03-12 02:00:40.559075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8916cdc8066a'
down_revision = '1d122d30c482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tlteam')
    op.add_column('wfh_pcs', sa.Column('tl', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wfh_pcs', 'users', ['tl'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wfh_pcs', type_='foreignkey')
    op.drop_column('wfh_pcs', 'tl')
    op.create_table('tlteam',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('agent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('token', mysql.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['agent'], ['agents.id'], name='tlteam_ibfk_1'),
    sa.ForeignKeyConstraint(['tl'], ['users.id'], name='tlteam_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
