"""edit req

Revision ID: 90eb57792a6f
Revises: 0a30e08b6a3e
Create Date: 2022-02-06 03:47:00.900411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90eb57792a6f'
down_revision = '0a30e08b6a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reqtype', 'reqstatue')
    op.add_column('requests', sa.Column('statue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'statue')
    op.add_column('reqtype', sa.Column('reqstatue', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
