"""edit departure

Revision ID: 98fc6c4becd6
Revises: d1f51d7cfab1
Create Date: 2022-01-26 16:01:19.918993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98fc6c4becd6'
down_revision = 'd1f51d7cfab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilitycheck', sa.Column('req_no', sa.String(length=250), nullable=True))
    op.drop_column('facilitycheck', 'agent')
    op.add_column('itcheck', sa.Column('req_no', sa.String(length=250), nullable=True))
    op.drop_column('itcheck', 'agent')
    op.add_column('securitycheck', sa.Column('req_no', sa.String(length=250), nullable=True))
    op.drop_column('securitycheck', 'agent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securitycheck', sa.Column('agent', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('securitycheck', 'req_no')
    op.add_column('itcheck', sa.Column('agent', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('itcheck', 'req_no')
    op.add_column('facilitycheck', sa.Column('agent', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('facilitycheck', 'req_no')
    # ### end Alembic commands ###
