"""edit facility check

Revision ID: 9b7472d73600
Revises: a4dbde8dd9c8
Create Date: 2022-02-04 03:23:50.340393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7472d73600'
down_revision = 'a4dbde8dd9c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilitycheck', sa.Column('pc', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('screens', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('desktop', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('labtop', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('cebox', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('jack', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('usb', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('rj11', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('oncell', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('proffess', sa.Boolean(), nullable=True))
    op.add_column('facilitycheck', sa.Column('comment', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilitycheck', 'comment')
    op.drop_column('facilitycheck', 'proffess')
    op.drop_column('facilitycheck', 'oncell')
    op.drop_column('facilitycheck', 'rj11')
    op.drop_column('facilitycheck', 'usb')
    op.drop_column('facilitycheck', 'jack')
    op.drop_column('facilitycheck', 'cebox')
    op.drop_column('facilitycheck', 'labtop')
    op.drop_column('facilitycheck', 'desktop')
    op.drop_column('facilitycheck', 'screens')
    op.drop_column('facilitycheck', 'pc')
    # ### end Alembic commands ###
