"""edit departure

Revision ID: 9d7d5244967f
Revises: 2598b8f045d8
Create Date: 2022-01-26 14:30:56.695979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7d5244967f'
down_revision = '2598b8f045d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilitycheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locker', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itcheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securitycheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('v_access', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('securitycheck')
    op.drop_table('itcheck')
    op.drop_table('facilitycheck')
    op.drop_table('departure')
    # ### end Alembic commands ###
