"""add TLs profiles

Revision ID: b4396d7a6d9e
Revises: 5027ead35a0c
Create Date: 2022-03-10 14:01:30.538979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4396d7a6d9e'
down_revision = '5027ead35a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('statue', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tls')
    # ### end Alembic commands ###
