"""edit requists

Revision ID: b9409b415248
Revises: 4343ca55eb66
Create Date: 2022-01-28 09:26:11.950521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9409b415248'
down_revision = '4343ca55eb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reqtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('req_type', sa.Integer(), nullable=True),
    sa.Column('req_title', sa.String(length=100), nullable=True),
    sa.Column('req_date', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['req_type'], ['reqtype.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('reqtype')
    # ### end Alembic commands ###
