"""edits

Revision ID: bb5629d1c074
Revises: 57c5a5906ab5
Create Date: 2022-07-23 17:56:22.756106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb5629d1c074'
down_revision = '57c5a5906ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('order_history', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock', 'orders_history', ['order_history'], ['id'])
    op.drop_column('stock', 'order_quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('order_quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'order_history')
    # ### end Alembic commands ###
