"""edit agents

Revision ID: bb73d09d9c33
Revises: 
Create Date: 2022-01-12 06:39:57.223909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb73d09d9c33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('l_name', sa.String(length=100), nullable=False))
    op.add_column('agents', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('agents', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('agents', sa.Column('phone', sa.String(length=100), nullable=True))
    op.add_column('agents', sa.Column('depart', sa.Integer(), nullable=False))
    op.add_column('agents', sa.Column('job_title', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'job_title')
    op.drop_column('agents', 'depart')
    op.drop_column('agents', 'phone')
    op.drop_column('agents', 'address')
    op.drop_column('agents', 'start_date')
    op.drop_column('agents', 'l_name')
    # ### end Alembic commands ###
