"""add leavers table

Revision ID: cb3edfe2af44
Revises: bb73d09d9c33
Create Date: 2022-01-18 13:37:36.416406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3edfe2af44'
down_revision = 'bb73d09d9c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leavers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('l_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('depart', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=250), nullable=True),
    sa.Column('sub_reason', sa.String(length=250), nullable=True),
    sa.Column('departure_type', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leavers')
    # ### end Alembic commands ###
