"""edit departure

Revision ID: d1f51d7cfab1
Revises: 37c4644e38ed
Create Date: 2022-01-26 15:09:01.920270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f51d7cfab1'
down_revision = '37c4644e38ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilitycheck', sa.Column('agent', sa.String(length=250), nullable=True))
    op.add_column('itcheck', sa.Column('agent', sa.String(length=250), nullable=True))
    op.add_column('securitycheck', sa.Column('agent', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('securitycheck', 'agent')
    op.drop_column('itcheck', 'agent')
    op.drop_column('facilitycheck', 'agent')
    # ### end Alembic commands ###
