"""add notifications

Revision ID: d391c18a0d6d
Revises: 2481ee5f6648
Create Date: 2022-02-15 03:12:17.659633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd391c18a0d6d'
down_revision = '2481ee5f6648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_notif_id', sa.Integer(), nullable=True))
    op.drop_constraint('notifications_ibfk_1', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_notif_id'], ['id'])
    op.drop_column('notifications', 'dep_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('dep_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_ibfk_1', 'notifications', 'users', ['dep_id'], ['id'])
    op.drop_column('notifications', 'user_notif_id')
    # ### end Alembic commands ###
