"""edit stock

Revision ID: d61f3cf10609
Revises: 29674099bb42
Create Date: 2022-02-15 01:15:52.479161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61f3cf10609'
down_revision = '29674099bb42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock', 'agents', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock', type_='foreignkey')
    op.drop_column('stock', 'assigned_to')
    # ### end Alembic commands ###
