"""add requists department

Revision ID: dc3723b7e81a
Revises: 4b42a8244f77
Create Date: 2022-02-07 04:01:50.209325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc3723b7e81a'
down_revision = '4b42a8244f77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requests_ibfk_4', 'requests', type_='foreignkey')
    op.drop_column('requests', 'depart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('depart_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('requests_ibfk_4', 'requests', 'department', ['depart_id'], ['id'])
    # ### end Alembic commands ###
