"""edit departure

Revision ID: f35143eab986
Revises: 35dd963c61b5
Create Date: 2022-01-26 12:55:50.060057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35143eab986'
down_revision = '35dd963c61b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility_check', sa.Column('locker', sa.Integer(), nullable=True))
    op.add_column('it_check', sa.Column('access', sa.Integer(), nullable=True))
    op.add_column('security_check', sa.Column('v_access', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('security_check', 'v_access')
    op.drop_column('it_check', 'access')
    op.drop_column('facility_check', 'locker')
    # ### end Alembic commands ###
